<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-V3TS40K" failures="2" tests="5" name="Test" time="51.634" errors="0" timestamp="2022-04-02T15:09:27 CEST">
  <testcase classname="tests.ValidateTitleTest" name="titleAssert" time="0.799"/>
  <testcase classname="tests.ValidateNavBarTest" name="titleAssert" time="1.153"/>
  <testcase classname="tests.LoginTest" name="login" time="3.284">
    <failure type="java.lang.AssertionError" message="expected [aida_ks@yahoo.com] but found [aidah1803@gmail.com]">
      <![CDATA[java.lang.AssertionError: expected [aida_ks@yahoo.com] but found [aidah1803@gmail.com]
at tests.LoginTest.login(LoginTest.java:45)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tests.ForgetPasswordTest" name="resetPass" time="2.709"/>
  <testcase classname="tests.LoginTest" name="login" time="1.442">
    <failure type="java.lang.AssertionError" message="expected [aida_ks@yahoo.com] but found [komora.aida@gmail.com]">
      <![CDATA[java.lang.AssertionError: expected [aida_ks@yahoo.com] but found [komora.aida@gmail.com]
at tests.LoginTest.login(LoginTest.java:45)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test -->
